seed: 42
dtype: float32
llms:
  - name: EleutherAI/pythia-160M
    revision: step142000
  - name: EleutherAI/pythia-160M
    revision: step143000 # last checkpoint
layer_indices_to_harvest: [8]
dataset:
  hf_dataset: PleIAs/common_corpus
  cache_dir: ".cache"
  sequence_length: 256
  harvest_batch_size: 4
  shuffle_buffer_size: 4_096
  n_batches_for_norm_estimate: 10
crosscoder:
  hidden_dim: 6144
  k: 20
train:
  learning_rate:
    initial_learning_rate: 5e-5
    last_pct_of_steps: 0.2
  batch_size: 512
  num_steps: 1_000
  save_dir: './checkpoints/l1_crosscoder'
  save_every_n_steps: 1000000 # don't save
  log_every_n_steps: 5
wandb:
  project: model-diffing
  entity: mars-model-diffing
