data:
  activations_iterator:
    layer_indices_to_harvest:
      - 8
    harvest_batch_size: 4
    sequence_tokens_iterator:
      name: common_corpus
      sequence_length: 256
  shuffle_buffer_size: 32_768
  batch_size: 32
llms:
  models:
    - name: EleutherAI/pythia-160M
      revision: step142000
    - name: EleutherAI/pythia-160M
      revision: step143000 # last checkpoint
wandb:
  name: topk_crosscoder_pythia_160M
crosscoder:
  hidden_dim: 6144
  k: 20
train:
  learning_rate:
    initial_learning_rate: 5e-5
    last_pct_of_steps: 0.2
  num_steps: 100_000
  save_dir: './checkpoints/topk_crosscoder_pythia_160M'
  save_every_n_steps: 1000000 # don't save
  log_every_n_steps: 5
