data:
  sequence_iterator:
    batch_size: 32
    classname: ConnorGemma2TokenSequenceLoader
  activations_harvester:
    llms:
      - name: google/gemma-2-2b
      - name: google/gemma-2-2b-it
    layer_indices_to_harvest: [13]
  activations_shuffle_buffer_size: 8_192
  cc_training_batch_size: 512
crosscoder:
  hidden_dim: 6144
train:
  wandb: True
  optimizer:
    initial_learning_rate: 5e-5
    last_pct_of_steps: 0.2
  l1_coef_max: 5
  l1_coef_n_steps: 1000
  num_steps: 10_000
  save_every_n_steps: 1000
  log_every_n_steps: 20
  log_visualizations_every_n_steps: 1000
experiment_name: l1_crosscoder_gemma_2_2b_layer_13
