seed: 42
dtype: float32
llms:
  - name: EleutherAI/pythia-160M
    revision: step142000
  - name: EleutherAI/pythia-160M
    revision: step143000 # last checkpoint
layer_indices_to_harvest:
  - 8
dataset:
  hf_dataset: PleIAs/common_corpus
  cache_dir: ".cache"
  sequence_length: 256
  harvest_batch_size: 32
  shuffle_buffer_size: 32_768
  n_batches_for_norm_estimate: 10
crosscoder:
  hidden_dim: 6144
train:
  learning_rate:
    initial_learning_rate: 5e-5
    last_pct_of_steps: 0.2
  lambda_max: 5
  lambda_n_steps: 1000
  batch_size: 8_192
  num_steps: 100_000
  save_dir: './checkpoints/l1_crosscoder'
  save_every_n_steps: 1000
  log_every_n_steps: 50
wandb:
  project: model-diffing
  entity: mars-model-diffing
