data:
  token_sequence_loader:
    type: HuggingfaceTextDatasetTokenSequenceLoader
    hf_dataset_name: "monology/pile-uncopyrighted"
    sequence_length: 256
  activations_harvester:
    llms:
      - name: EleutherAI/pythia-160M
        revision: step142000
      - name: EleutherAI/pythia-160M
        revision: step143000 # last checkpoint
    harvesting_batch_size: 1
crosscoder:
  n_latents: 6144
train:
  num_steps: 10_000
  batch_size: 32
  final_lambda_s: 5
  lambda_s_n_steps: 1000
  save_every_n_steps: 1000
  log_every_n_steps: 50
experiment_name: l1_crosscoder_example
hookpoints: ["blocks.8.hook_resid_post"]